name: 'bookstore'
services:
  bookstore-postgres:
    image: postgres:17-alpine
    container_name: bookstore-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - bookstore-pgdata:/var/lib/postgresql/data

volumes:
  bookstore-pgdata: