name: 'bookstore'
services:
  bookstore:
    image: sivaprasadreddy/bookstore
    #build: .
    container_name: bookstore
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://bookstore-postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      MANAGEMENT_TRACING_ENABLED: "${TRACING_ENABLED}"
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://tempo:9411
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - bookstore-postgres
    deploy:
      resources:
        limits:
          memory: 1024m
    labels:
      logging: "promtail"

  bookstore-postgres:
    image: postgres:17-alpine
    container_name: bookstore-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:8.2.1
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: unless-stopped